### ISSUE TITLE
TCGA .isoforms.quantification.txt file extension change

### ISSUE THREAD

**Issue by programmingprincess** [rptashkin/TCGA_support-scripts#1]
Hi, I believe that the isoforms file extension for files downloaded from TCGA miRNA data is now isoforms.quantification.txt. In `get_mature_miR_matrix.R`, the file extension is still set to isoform.quantification.txt (just missing an "s" in isoforms"). Not sure if other people have encountered this error.

**Comment by rptashkin** [comment]
Thanks, will merge!
